[package]
name = "rs-tutorial"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
log = "0.4.22"
serde_json = "1.0.132"
env_logger = "0.11.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
